name: appwrite_model_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  code_builder: ^4.10.1
  dart_helper_utils: ^5.1.0
  dart_style: ^3.0.1
  path: ^1.9.1
  result_type: ^1.0.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  appwrite_gen: generate
